"""Research pipeline building blocks for model development and experimentation."""

from .baselines import BaselinePrediction, MajorityClassBaseline, PersistenceBaseline
from .diagnostics import (
    build_experiment_integrity_proof,
    build_search_diagnostics,
    build_training_experiment_diagnostics,
    resolve_integrity_payload,
)
from .defaults import (
    ResearchDefaults,
    default_baseline_names,
    default_threshold_list,
    get_builtin_research_defaults,
    resolve_research_defaults,
)
from .execution import EvaluationPipeline, ExperimentRunner, SearchCandidateConfig, SearchRunner, TrainingPipeline, WalkForwardSplitter
from .experiment_store import ExperimentStore
from .feature_selection import (
    CorrelationFeatureSelector,
    FeatureSelectorResult,
    FullSetFeatureSelector,
    VarianceFeatureSelector,
    build_feature_selector,
)
from .feature_sets import (
    FeatureSetDefinition,
    build_feature_inventory,
    build_named_feature_sets,
    classify_feature_group,
    enrich_inventory_with_named_sets,
    get_feature_set_description,
    get_feature_set_display_name,
    get_group_display_name,
    group_features_by_prefix,
    is_raw_market_column,
    is_target_or_future_column,
    resolve_feature_sets,
)
from .feature_study import FeatureStudyRunner
from .labels import (
    BinaryTargetSpec,
    FixedHorizonDirectionSpec,
    LegacyRuntimeDirectionSpec,
    NeutralBandLabelSpec,
    ReturnThresholdLabelSpec,
    VolatilityAdjustedMoveSpec,
    build_binary_target_labels,
    build_fixed_horizon_direction_labels,
    build_legacy_runtime_direction_labels,
    build_neutral_band_labels,
    build_observed_persistence_labels,
    build_return_threshold_labels,
    build_volatility_adjusted_move_labels,
    serialize_target_spec,
)
from .preprocessing import ResearchPreprocessor
from .promotion import PromotionManifest, get_default_promoted_model_path
from .catalog import (
    build_stage5_preset_catalog,
    build_stage5_target_catalog_rows,
    build_stage5_target_specs,
    describe_stage5_target,
    get_stage5_preset_description,
    get_stage5_preset_display_name,
    list_stage5_preset_names,
    resolve_stage5_preset_definitions,
)
from .schemas import (
    CandidateArtifact,
    ExperimentResult,
    FeatureInventoryRow,
    FeatureStudyFoldSelection,
    FeatureStudyRequest,
    FeatureStudyResult,
    FeatureStudySetResult,
    FoldMetrics,
    PredictionArtifacts,
    ResearchExperimentRequest,
    ResearchSplit,
    SearchCandidateSummary,
    SearchRequest,
    SearchResult,
    TrainingExperimentRequest,
    TrainingExperimentResult,
    TargetStudyRequest,
    TargetStudyResult,
    TargetStudyTargetResult,
    TargetSummary,
    TrainerOutput,
)
from .target_study import MaterializedTarget, TargetStudyRunner, build_target_result_stub
from .training_experiment import (
    build_threshold_summary_rows,
    select_best_threshold,
    summarize_selected_threshold_metrics,
)
from .trainers import CurrentEnsembleTrainer, LSTMTrainer, ResearchTrainer, TrainerRegistry

__all__ = [
    "BaselinePrediction",
    "BinaryTargetSpec",
    "CandidateArtifact",
    "CorrelationFeatureSelector",
    "CurrentEnsembleTrainer",
    "default_baseline_names",
    "default_threshold_list",
    "EvaluationPipeline",
    "ExperimentResult",
    "ExperimentRunner",
    "ExperimentStore",
    "FeatureInventoryRow",
    "FeatureSelectorResult",
    "FeatureSetDefinition",
    "FeatureStudyFoldSelection",
    "FeatureStudyRequest",
    "FeatureStudyResult",
    "FeatureStudyRunner",
    "FeatureStudySetResult",
    "FixedHorizonDirectionSpec",
    "FoldMetrics",
    "FullSetFeatureSelector",
    "LegacyRuntimeDirectionSpec",
    "LSTMTrainer",
    "MajorityClassBaseline",
    "MaterializedTarget",
    "NeutralBandLabelSpec",
    "PredictionArtifacts",
    "PromotionManifest",
    "PersistenceBaseline",
    "ResearchTrainer",
    "ResearchExperimentRequest",
    "ResearchPreprocessor",
    "ResearchSplit",
    "SearchCandidateConfig",
    "SearchCandidateSummary",
    "SearchRequest",
    "SearchResult",
    "SearchRunner",
    "ReturnThresholdLabelSpec",
    "TargetStudyRequest",
    "TargetStudyResult",
    "TargetStudyRunner",
    "TargetStudyTargetResult",
    "TargetSummary",
    "ResearchDefaults",
    "TrainingExperimentRequest",
    "TrainingExperimentResult",
    "TrainerOutput",
    "TrainerRegistry",
    "TrainingPipeline",
    "VarianceFeatureSelector",
    "VolatilityAdjustedMoveSpec",
    "WalkForwardSplitter",
    "build_feature_inventory",
    "build_feature_selector",
    "build_named_feature_sets",
    "build_binary_target_labels",
    "build_fixed_horizon_direction_labels",
    "build_legacy_runtime_direction_labels",
    "build_neutral_band_labels",
    "build_observed_persistence_labels",
    "build_return_threshold_labels",
    "build_search_diagnostics",
    "build_experiment_integrity_proof",
    "build_training_experiment_diagnostics",
    "build_target_result_stub",
    "build_volatility_adjusted_move_labels",
    "classify_feature_group",
    "enrich_inventory_with_named_sets",
    "get_feature_set_description",
    "get_default_promoted_model_path",
    "get_feature_set_display_name",
    "get_group_display_name",
    "group_features_by_prefix",
    "is_raw_market_column",
    "is_target_or_future_column",
    "resolve_feature_sets",
    "resolve_research_defaults",
    "resolve_integrity_payload",
    "get_builtin_research_defaults",
    "build_threshold_summary_rows",
    "build_stage5_preset_catalog",
    "build_stage5_target_catalog_rows",
    "build_stage5_target_specs",
    "get_stage5_preset_description",
    "get_stage5_preset_display_name",
    "describe_stage5_target",
    "list_stage5_preset_names",
    "resolve_stage5_preset_definitions",
    "select_best_threshold",
    "serialize_target_spec",
    "summarize_selected_threshold_metrics",
]
